apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bundle.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "bundle.fullname" . }}
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "true"
        - name: APP_NAME
          value: "sap-commerce-cloud"
        - name: APP_ID
          value: "0e412d8e-af8d-4fbd-82a5-d518eea7aef2"
        - name: TENANT_ID
          value: "3e64ebae-38b5-46a0-b1ed-9ccee153a0ae"

