apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bundle.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "bundle.fullname" . }}
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "true"
        - name: APP_NAME
          value: "sap-marketing-cloud"
        - name: APP_ID
          value: "03592900-5987-4d47-a13d-c0d7ad44a37f"
